easy_admin:
    site_name: '<em style="font-size: 80%; color: blue;">IT.Nomade Admin</em>'
    entities:
        # List the entity class name you want to manage
        - App\Entity\Quote
        - App\Entity\Order
        - App\Entity\User
