version: '3.1'
services:
  it_nomade_db:
    image: mysql:5.7
    container_name: itnomade-db
    volumes:
      - my-datavolume:/var/lib/mysql
    #restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=papamoris76
      - MYSQL_DATABASE=itnomade
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      #- MYSQL_USER=itnomade_db_user
    ports:
      - "3309:3306"

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/keys:/etc/nginx/certs
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/keys:/etc/nginx/certs
    env_file:
      - .env

volumes:
   my-datavolume:
#    user: ${LOCAL_USER}